name: Jekyll Build

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.x

    - name: Install dependencies
      run: |
        gem install bundler
        cd docs
        bundle install --path vendor/bundle
        cd ..

    - name: Build the site
      run: |
        cd docs
        npm run build-docs
        bundle exec jekyll build
        cd ..

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_site
